#!/usr/bin/env python3
"""
Writeback Review — Flask App
Traxis Manufacturing

Small Flask app for reviewing and approving writeback candidates
generated by the Pattern Accumulator. Displays candidates with
evidence (jobs, confidence, values) and allows Approve/Reject.

Usage:
  python writeback_review.py
  python writeback_review.py --port 8075
  python writeback_review.py --candidates path/to/writeback_candidates.jsonl
"""

import json
import os
import sys
from datetime import datetime

from flask import Flask, render_template, request, redirect, url_for, jsonify

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Default candidates file locations
DEFAULT_CANDIDATES_PATHS = [
    r"D:\Dropbox\MACHINE COMM Traxis\Programming Sessions\diffs\writeback_candidates.jsonl",
]

app = Flask(__name__, template_folder=SCRIPT_DIR)


def find_candidates_path():
    """Find the writeback candidates JSONL file."""
    for path in DEFAULT_CANDIDATES_PATHS:
        if os.path.isfile(path):
            return path
    return None


def read_candidates(filepath):
    """Read all writeback candidates from JSONL file."""
    candidates = []
    if not filepath or not os.path.isfile(filepath):
        return candidates
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            for i, line in enumerate(f):
                line = line.strip()
                if line:
                    rec = json.loads(line)
                    rec['_index'] = i
                    candidates.append(rec)
    except Exception:
        pass
    return candidates


def write_candidates(filepath, candidates):
    """Write all candidates back to JSONL file."""
    try:
        with open(filepath, 'w', encoding='utf-8') as f:
            for c in candidates:
                # Remove internal index before writing
                rec = {k: v for k, v in c.items() if not k.startswith('_')}
                f.write(json.dumps(rec, default=str) + "\n")
    except Exception as e:
        print(f"Error writing candidates: {e}")


# Read patterns file for additional context
def read_patterns(candidates_path):
    """Read patterns.jsonl from the same directory."""
    if not candidates_path:
        return []
    patterns_path = os.path.join(
        os.path.dirname(candidates_path), "patterns.jsonl")
    patterns = []
    if os.path.isfile(patterns_path):
        try:
            with open(patterns_path, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line:
                        patterns.append(json.loads(line))
        except Exception:
            pass
    return patterns


@app.route("/")
def index():
    """Main page — list all writeback candidates."""
    filepath = app.config.get('CANDIDATES_PATH') or find_candidates_path()
    candidates = read_candidates(filepath)
    patterns = read_patterns(filepath)

    # Build pattern lookup for additional context
    pattern_lookup = {p.get("pattern_id", ""): p for p in patterns}

    # Enrich candidates with pattern data
    for c in candidates:
        pid = c.get("pattern_id", "")
        if pid in pattern_lookup:
            c['_pattern'] = pattern_lookup[pid]

    # Group by status
    pending = [c for c in candidates if c.get("status") == "pending_approval"]
    approved = [c for c in candidates if c.get("status") == "approved"]
    rejected = [c for c in candidates if c.get("status") == "rejected"]
    written = [c for c in candidates if c.get("status") == "written"]

    return render_template("writeback_review.html",
                           pending=pending,
                           approved=approved,
                           rejected=rejected,
                           written=written,
                           total=len(candidates),
                           now=datetime.now().strftime("%Y-%m-%d %H:%M"))


@app.route("/update", methods=["POST"])
def update_status():
    """Update a candidate's status (approve/reject)."""
    filepath = app.config.get('CANDIDATES_PATH') or find_candidates_path()
    if not filepath:
        return redirect(url_for("index"))

    candidates = read_candidates(filepath)
    pattern_id = request.form.get("pattern_id", "")
    new_status = request.form.get("status", "")

    if new_status not in ("approved", "rejected", "pending_approval", "written"):
        return redirect(url_for("index"))

    # Find and update the candidate
    for c in candidates:
        if c.get("pattern_id") == pattern_id:
            c["status"] = new_status
            c["reviewed_at"] = datetime.now().isoformat(timespec="seconds")
            break

    write_candidates(filepath, candidates)
    return redirect(url_for("index"))


@app.route("/api/candidates")
def api_candidates():
    """JSON API endpoint for candidates."""
    filepath = app.config.get('CANDIDATES_PATH') or find_candidates_path()
    candidates = read_candidates(filepath)
    return jsonify(candidates)


def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="Writeback Review Flask App")
    parser.add_argument("--port", type=int, default=8075)
    parser.add_argument("--candidates", help="Path to candidates JSONL")
    parser.add_argument("--host", default="127.0.0.1")
    args = parser.parse_args()

    if args.candidates:
        app.config['CANDIDATES_PATH'] = args.candidates

    print(f"Writeback Review starting on http://{args.host}:{args.port}")
    app.run(host=args.host, port=args.port, debug=False)


if __name__ == "__main__":
    main()
